### ISSUE TITLE
Subsumed by self.structuredClone?

### ISSUE THREAD

**Issue by littledan** [domenic/proposal-arraybuffer-transfer#3]
If HTML adds a [`structuredClone` method](https://github.com/whatwg/html/pull/3414), would it still make sense to expose an `ArrayBuffer.transfer` operation? It seems that you could use `structuredClone` for very similar purposes, though it's only available on the web. cc @surma

**Comment by domenic** [comment]
I think there's value in saying what you mean, and exposing the appropriate low-level primitives.

Having to use

```js
const transferred = structuredClone(arrayBuffer, [arrayBuffer]);
```

to convey the semantic of "transfer this array buffer" is pretty opaque.

And, tying up the low-level ability to transfer array buffers inside the higher-level, recursive-object-graph-crawling, multi-function structured cloning algorithm is pretty silly. I'd rather move toward high-level features like structured clone be implementable in JavaScript, by making it possible to transfer individual transferables, instead of inverting things and using structured clone to get at low-level functionality.

**Comment by domenic** [comment]
Withdrawing the proposal after all, in favor of `self.structuredClone()` and https://github.com/tc39/proposal-resizablearraybuffer
